language: python
python:
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- '3.7'
matrix:
  allow_failures:
    - python: '3.3'
    - python: '3.7'
install:
- pip install flake8==2.5.0
- pip install -U setuptools
script:
- flake8 . --max-complexity 5 --max-line-length 99 --ignore E201,E202,E402
- python setup.py test
env:
- secure: VcMgjDkCmUbHGEUr0TMkX4A6dfghr+u54ygSfsSr+o1tJcQhaPcoFM2Uw3f/wXdrMoISFDax7yqmwIaFN/1nVK1sb2GeQ715kPpVUQMiXzQdbtRIWHF3qpnANmKlj1qBHbHznT/NT+3q5MwYuAomgmcre7iykW63ilC+IGpit4G82tFFYqBYiBJDW3IU+ji+7SQqK8UHOsU6q4gat20d1cgbHNccixJDDF+7umfy1VlBYdGbLYB3Q//XUds5nXK+cRSW5U6dReO2QXbC1mc2e6NcKN+zTGKaIGaARzXg+jdBsg/VRzGmtdH80knIB4CcSXlztQKXb1N7wYHemEbNdHGUiQSs4AwRIPckzPxkB31kHraSi8BTsZ+ae4UvH3Fnu9AMeBF6DH3KSGG3fa3lx5FRP4M5JMFIHOTB2u0JLv3h0H1y/UntzJuKgtzOwvxWdlJt0Kb/4hqYse8g4S6wW91PJHBKh+HmaMCK5uqR6hHH4wuWd40a98PbuTyBRoqAki06CcdmfN09a5NvCorXdgu55ojwQX45HvyAd+NNZbhV7omZKv+qxYvzwEbw4TnoyU/IUjgli9VPPAlNpgG3XpCSWRYThlY6vVLDnePnfrqzFL6q2JQbR4t/N0ZfYLlLub9f4v8/tffIj2DWOZH6aZ3O4TdWlEd8BMCoQiJMJX8=
notifications:
  email: false
deploy:
  provider: pypi
  user: jwg
  on:
    python: '3.5'
  password:
    secure: vTJRAMKPo1qtA7TjsRfOyJZYZZlWs7D7pwscuJWGDyiYQMfBJm9lUOJj3Mqt6WEEdENcB4ZOhAVE1n9IvZzpB1lTF2YwIm7xQ6lhWofOQusjuLBJ3lu0wQWUkphb3YMY5+Om3I/2+tz/P87/W409i2HW3FlhMe+W4yeDg+wXnsS3jGvPxKRqBHJsoAeAgsPP7m6h0IJ3pG08Ew8uJg2ph/HWn0zHLrZMbP8WIphcXpUkFcluCTNcrAI6weDjy3tnVhXV1j4X3L42M+8Hg6tYvxCTUVbWiafC5GgO/ILoXCeejaXawHEJ6vuEWdK1JHncH76dFArjyN/jF0KIjVkq+ONTPbJCQpIKcpvT9r6zCxh9wEeXdTdvoomuVyccanuGjlnR7vZXW2UlCavoOVar2E3FxjJYcjNVmL+awXjWGTCMYsdvB7LqanDwP4ItEHGjmuP0M+CZFc+2TZrVgZRPRaKbVnPlNpvTLiRRGt8Y56RZudTsfR3nWy/fcMmRYDQ80roVamS3JmSzCd8dgAF57xmqz9S0ov2D+Moti4KO5UBksIc+c2XT4JjpwkHXeebhwalCwyBoZwKje9X3V1t4TXFkWHHwahkL3xwuSgpFLrXcP9VdGf0lQXPNOvLIUrn6ZnrrEt9QGflkeadpIfeOCxBsgNmrpg9ulRWnhCBBe3s=
